

import 'package:flutter_sample/constants/app_strings.dart';

const Map<String, String> en_US = {
  AppStrings.getStarted: 'Get Started',
  AppStrings.requestCancelled: 'Request cancelled',
  AppStrings.notSubType: 'is not a subtype of',
  AppStrings.unableToProcessData: 'Unable to process data',
  AppStrings.processData: 'process data',
  AppStrings.connectionTimeOut: 'Connection timeout',
  AppStrings.timeOut: 'Time out',
  AppStrings.notFound: 'Not Found',
  AppStrings.requestTimeOut: 'Request Time out',
  AppStrings.internalServerError: 'Internal Server Error',
  AppStrings.serviceUnavailable: 'Service Unavailable',
  AppStrings.somethingWorg: 'Something is wrong',
  AppStrings.socketExceptions: 'Socket Exception',
  AppStrings.unExceptedExption: 'Unexpected Exceptions',
  AppStrings.diveBackIn: 'Dive Back In',
  AppStrings.formetException: 'Format Exceptions',
  AppStrings.connectionRefused: 'Connection refused',
  AppStrings.networkUnReachable: 'Network is unreachable',
  AppStrings.serverUnderMaintance: 'Something went wrong. Please try again later',
  AppStrings.pleaseTryAgain: 'Please try again later',
  AppStrings.falidToHostLookup: 'Failed host lookup',
  AppStrings.noInternetConnection: 'No Internet Connection',
  AppStrings.unAuthorizeRequest: 'Unauthorised Request',
  AppStrings.emailCantBeEmpty: 'Email can\'t be empty!',
  AppStrings.otpCantBeEmpty: 'OTP can\'t be empty!',
  AppStrings.pleaseEnterAValidEmailAddress: 'Please enter a valid email address!',
  AppStrings.pleaseEnterAValidOTP: 'Please enter a valid OTP!',
  AppStrings.phoneNoCantBeEmpty: 'Phone Number can\'t be empty!',
  AppStrings.pleaseEnterAValidPhoneNumber: 'Please enter a valid Phone Number!',
  AppStrings.passwordCantBeEmpty: 'Password can\'t be empty!',
  AppStrings.passwordMustContainWarning: 'Password should be at least 8 characters and must contain one uppercase, one lowercase, one numeric, and one special character',
  AppStrings.confirmPasswordCantBeEmpty: 'Confirm Password can\'t be empty!',
  AppStrings.confirmPasswordDoesntMatch: 'Confirm Password doesn\'t match',
  AppStrings.logout: 'Logout',
  AppStrings.cantBeEmpty: 'can\'t be empty',
  AppStrings.cardNumberIsInvalid: 'Card Number is invalid',
  AppStrings.cardNumberEmpty: 'Card Number can\'t be empty',
  AppStrings.cvvEmpty: 'CVV can\'t be empty',
  AppStrings.cvvIsInvalid: 'CVV is invalid',
  AppStrings.expiryDateEmpty: 'Expiry Date can\'t be empty',
  AppStrings.expiryMonthIsInvalid: 'Expiry month is invalid',
  AppStrings.expiryYearIsInvalid: 'Expiry year is invalid',
  AppStrings.cardHasExpired: 'Card has expired',
  AppStrings.nameEmptyValidation: 'Name can\'t be empty',
  AppStrings.amountEmptyValidation: 'Amount can\'t be empty',
  AppStrings.visa: 'Visa',
  AppStrings.masterCard: 'Master',
  AppStrings.verve: 'Verve',
  AppStrings.americanExpress: 'American Express',
  AppStrings.discover: 'Discover',
  AppStrings.dinersClub: 'Diners Club',
  AppStrings.jcb: 'JCB',
  AppStrings.others: 'Others',

  AppStrings.selectPickImage: 'Click/Pick Image',
  AppStrings.gallery: 'Gallery',
  AppStrings.camera: 'Camera',
  AppStrings.noDataFound: 'No Data Found',
  AppStrings.areYourSureYouWantToLogout: 'Are you sure you want to logout?',
  AppStrings.areYourSureYouWantToDeleteAccount: 'Are you sure you want to delete Account?',
  AppStrings.yes: 'Yes',
  AppStrings.no: 'No',
  AppStrings.next: 'Next',
  AppStrings.cancel: 'Cancel',
  AppStrings.createNewPassword: 'Create New Password',
  AppStrings.yourNewPasswordMustBeUnique: 'Your new password must be unique from those previously used.',
  AppStrings.forgotPassword: 'Forgot Password',
  AppStrings.signInToYourAccount: 'Sign in to your account',
  AppStrings.usernameEmail: 'Username/Email',

  AppStrings.firstName: 'First Name',
  AppStrings.lastName: 'Last Name',
  AppStrings.email: 'Email',
  AppStrings.password: 'Password',
  AppStrings.newPassword: 'New Password',
  AppStrings.confirmPassword: 'Confirm Password',
  AppStrings.signIn: 'Sign in',
  AppStrings.signUp: 'Sign up',
  AppStrings.forgotYourPassword: 'Forgot your password?',
  AppStrings.dontHaveAnAccount: 'Don’t have an account? ',
  AppStrings.haveAnAccount: 'Have an account? ',
  AppStrings.welcome: 'Welcome!',
  AppStrings.registerHere: 'Register here!',
  AppStrings.registerYourAccount: 'Register your account',
  AppStrings.create: 'Create',
  AppStrings.dontWorryItOccurs: 'Don\'t worry! It occurs. Please enter the email address linked with your account.',
  AppStrings.sendCode: 'Send Code',
  AppStrings.otpVerification: 'OTP Verification',
  AppStrings.enterTheVerificationCode: 'Enter the verification code we just sent on your email address.',
  AppStrings.verify: 'Verify',
  AppStrings.didntRecievedCode: 'Didn’t received code? ',
  AppStrings.resend: 'Resend',
  AppStrings.otpVerified: 'OTP Verified!',
  AppStrings.passwordChanged: 'Password Changed!',
  AppStrings.yourOtpHasBeenVerified: 'Your OTP has been verified and let’s get your amenities fulfilled.',
  AppStrings.yourPasswordHasBeenChanged: 'Your password has been changed successfully.',
  AppStrings.resetPassword: 'Reset Password',
  AppStrings.or: 'or ',

  AppStrings.resendIn: 'Resend in',
  AppStrings.sec: 'sec',
  AppStrings.backToSignIn: 'Back to Sign in',
  AppStrings.home: 'Home',
  AppStrings.iCard: 'I Card',
  AppStrings.categories: 'Categories',
  AppStrings.seeAll: 'See All',
  AppStrings.settings: 'Settings',
  AppStrings.english: 'English',
  AppStrings.hebrew: 'Hebrew',
  AppStrings.hello: 'Hello!',
  AppStrings.dontMissTheChanceToScratch: 'Don’t miss the chance to Scratch the Card',
  AppStrings.recentlyViewed: 'Recently Viewed',
  AppStrings.customCards: 'Custom Cards',
  AppStrings.allCategories: 'All Categories',
  AppStrings.purchasedBoards: 'Purchased Boards',
  AppStrings.personalizedBoards: 'Personalized Boards',
  AppStrings.recommendedScratch: 'Recommended Scratch',
  AppStrings.exp: 'Exp ',
  AppStrings.purchaseDate: 'Purchase Date ',
  AppStrings.download: 'Download',
  AppStrings.profile: 'Profile',
  AppStrings.contactScratch: 'Contact Scratchy',
  AppStrings.transactionDetails: 'Transaction Details',
  AppStrings.deleteAccount: 'Delete Account',
  AppStrings.faq: 'FAQ',
  AppStrings.changePassword: 'Change Password',
  AppStrings.notificationPreferences: 'Notification Preferences',
  AppStrings.termsAndConditions: 'Terms And Conditions',
  AppStrings.privacyPolicy: 'Privacy Policy',
  AppStrings.howCanWeHelpYou: 'How can we help you?',
  AppStrings.pleaseLetUsKnowWhyAreYou: 'Please let us know why are you deleting your account?',
  AppStrings.search: 'Search',
  AppStrings.payNow: 'Pay Now',
  AppStrings.prefferedPaymentMethods: 'Preferred Payment Methods',
  AppStrings.cardsUPIAndMore: 'Cards, UPI & More',
  AppStrings.price: 'Price',
  AppStrings.pay: 'Pay',
  AppStrings.card: 'Card',
  AppStrings.coinCurrency: 'Coin currency ',
  AppStrings.addMore: 'Add More',
  AppStrings.addCard: 'Add Card',
  AppStrings.cardNumber: 'Card Number',
  AppStrings.nameOnCard: 'Name on Card',
  AppStrings.expiryDate: 'Expiry Date',
  AppStrings.cvv: 'CVV',
  AppStrings.payWithInstalledAppOrUseAnother: 'Pay with installed app, or use others',
  AppStrings.save: 'Save',
  AppStrings.name: 'Name',
  AppStrings.maskedCardNumber: '****',
  AppStrings.maskedExpiry: 'MM/YY',
  AppStrings.noCardsFound: 'No Cards Found',
  AppStrings.scratched: 'Scratched',

  AppStrings.aboutUs: 'About Us',
  AppStrings.fullName: 'Full Name',
  AppStrings.emailId: 'Email id',
  AppStrings.phoneNumber: 'Phone Number',
  AppStrings.address: 'Address',
  AppStrings.editProfile: 'Edit Profile',
  AppStrings.submit: 'Submit',
  AppStrings.skip: 'Skip',
  AppStrings.gender: 'Gender',
  AppStrings.popularCategories: 'Popular Categories',
  AppStrings.warning: 'Warning!',
  AppStrings.totalNoOfPersonalizedBoard: 'Total no of Personalized Board',
  AppStrings.totalNoOfCategoriesBoard: 'Total no of Categories Board',
  AppStrings.createYourOwnPersonlisedCards: 'Create your own Personalised Cards',
  AppStrings.cardLimit: 'Card Limit',
  AppStrings.getNow: 'Get Now',
  AppStrings.personalisedCards: 'Personalised Cards',
  AppStrings.previousCreatedCards: 'Previous Created Cards',
  AppStrings.personalisedQuestionnaire: 'Personalised Questionnaire',
  AppStrings.enterMessage: 'Enter Message',
  AppStrings.noQuestionsFound: 'No Questions Found',

  AppStrings.youNeedToPayForThisScratchCard: 'You need to pay for this scratch card',
  AppStrings.areYouSure: 'Are you sure?',
  AppStrings.youWantToSubmitTheResponse: 'You want to submit the response?',
  AppStrings.youWantToAddSupportTicket: 'You want to add support ticket?',
  AppStrings.confirm: 'Confirm',
  AppStrings.pleaseSelectAnOption: 'Please Select an Option',
  AppStrings.transactionHistory: 'Transaction History',
  AppStrings.transactionAmount: 'Transaction Amount',
  AppStrings.transactionDate: 'Transaction Date',
  AppStrings.transactionId: 'Transaction Id',
  AppStrings.orderId: 'Order Id',
  AppStrings.giveRating: 'Give Rating',
  AppStrings.rating: 'RATING!',
  AppStrings.add: '+Add',
  AppStrings.id: 'Id',
  AppStrings.date: 'Date',
  AppStrings.addTicket: 'Add Ticket',
  AppStrings.title: 'Title',
  AppStrings.description: 'Description',
  AppStrings.createdOn: 'Created on:',
  AppStrings.typeAMessage: 'Type a message...',
  AppStrings.admin: 'Admin',
  AppStrings.dateOfBirth: 'Date of Birth',
  AppStrings.noTicketsFound: 'No Tickets Found',
  AppStrings.youWantToMarkThisTicketAsComplete: 'You want to mark this Ticket as complete',
  AppStrings.cost: 'Cost',
  AppStrings.type: 'Type',
  AppStrings.ageGroup: 'Age group',
  AppStrings.manageSubscription: 'Manage Subscription',
  AppStrings.notifications: 'Notifications',
  AppStrings.clear: 'Clear',
  AppStrings.payPal: 'PayPal',
  AppStrings.purchase: 'Purchase',
  AppStrings.youWantToClearNotifications: 'You want to clear Notifications',
  AppStrings.connectionError: 'Connection Error',
  AppStrings.male: 'Male',
  AppStrings.female: 'Female',
  AppStrings.paymentFailed: "We were unable to process your payment. Please check try again.",
  AppStrings.payViaCrypto: "Pay via Crypto",
  AppStrings.continueText: "Continue",
  AppStrings.note: "Note",
  AppStrings.cryptoDialogDescriptionText: "To purchase Premium via cryptocurrency (Tether/Ethereum), please contact the Admin through 'Contact Scratchy'.",
  AppStrings.thePurchasedBoardIsExpired: "The Purchased Board is Expired. You need to purchase premium membership to scratch cards. Do you want to buy Premium?",
  AppStrings.youAreSubscribedToThePremiumMembership: "You are subscribed to the Premium Membership",
  AppStrings.inAppPurchase: "In-App Purchase",
  AppStrings.buyByCrypto: "Buy By Crypto",
  AppStrings.info: "Info",
  AppStrings.areYouSureYouWantToGetThisBoard: "Are you sure you want to get this board?",



};