import 'package:flutter_sample/constants/export.dart';

const Map<String, String> he_IL = {
  AppStrings.getStarted: 'התחל',
  AppStrings.requestCancelled: 'הבקשה בוטלה',
  AppStrings.notSubType: 'אינו מסוג של',
  AppStrings.unableToProcessData: 'לא ניתן לעבד את הנתונים',
  AppStrings.processData: 'לעבד נתונים',
  AppStrings.connectionTimeOut: 'זמן החיבור פג',
  AppStrings.timeOut: 'הזמן הסתיים',
  AppStrings.notFound: 'לא נמצא',
  AppStrings.requestTimeOut: 'זמן תגובת השרת הסתיים',
  AppStrings.internalServerError: 'שגיאת שרת פנימית',
  AppStrings.serviceUnavailable: 'השירות אינו זמין',
  AppStrings.somethingWorg: 'משהו לא בסדר',
  AppStrings.socketExceptions: 'שגיאת java',
  AppStrings.unExceptedExption: 'שגיאה בלתי צפויה',
  AppStrings.diveBackIn: 'צלול חזרה פנימה!',
  AppStrings.formetException: 'פורמט לא נתמך',
  AppStrings.connectionRefused: 'החיבור נדחה',
  AppStrings.networkUnReachable: 'הרשת לא נגישה',
  AppStrings.serverUnderMaintance: 'משהו השתבש. אנא נסה שוב מאוחר יותר',
  AppStrings.pleaseTryAgain: 'אנא נסה שוב מאוחר יותר',
  AppStrings.falidToHostLookup: 'חיפוש הוסט נכשל',
  AppStrings.noInternetConnection: 'אין חיבור לאינטרנט',
  AppStrings.unAuthorizeRequest: 'הבקשה לא מורשית',
  AppStrings.emailCantBeEmpty: 'כתובת דוא"ל לא יכולה להיות ריקה!',
  AppStrings.otpCantBeEmpty: 'סיסמה חד פעמית לא יכולה להיות ריקה!',
  AppStrings.pleaseEnterAValidEmailAddress: 'אנא הזן כתובת דוא"ל חוקית!',
  AppStrings.pleaseEnterAValidOTP: 'אנא הזן סיסמה חד פעמית חוקית!',
  AppStrings.phoneNoCantBeEmpty: 'מספר טלפון לא יכול להיות ריק!',
  AppStrings.pleaseEnterAValidPhoneNumber: 'אנא הזן מספר טלפון חוקי!',
  AppStrings.passwordCantBeEmpty: 'סיסמה לא יכולה להיות ריקה!',
  AppStrings.passwordMustContainWarning: 'סיסמה צריכה להכיל לפחות 8 תווים ויש לכלול אות גדולה אחת באנגלית, אות קטנה אחת באנגלית, ספרה אחת ותו מיוחד אחד',
  AppStrings.confirmPasswordCantBeEmpty: 'אימות סיסמה לא יכול להיות ריקה!',
  AppStrings.confirmPasswordDoesntMatch: 'אימות סיסמה לא תואם',
  AppStrings.logout: 'התנתק',
  AppStrings.cantBeEmpty: 'לא יכול להיות ריק',

  AppStrings.cardNumberIsInvalid: 'מספר כרטיס לא חוקי',
  AppStrings.cardNumberEmpty: 'מספר כרטיס לא יכול להיות ריק',
  AppStrings.cvvEmpty: 'לא יכול להיות CVV ריק',
  AppStrings.cvvIsInvalid: 'CVV לא חוקי',
  AppStrings.expiryDateEmpty: 'תאריך תפוגה לא יכול להיות ריק',
  AppStrings.expiryMonthIsInvalid: 'חודש תפוגה לא חוקי',
  AppStrings.expiryYearIsInvalid: 'שנת תפוגה לא חוקית',
  AppStrings.cardHasExpired: 'הכרטיס פג תוקף',
  AppStrings.nameEmptyValidation: 'שם לא יכול להיות ריק',
  AppStrings.amountEmptyValidation: 'סכום לא יכול להיות ריק',
  AppStrings.visa: 'ויזה',
  AppStrings.masterCard: 'מאסטרקארד',
  AppStrings.verve: 'Verve',
  AppStrings.americanExpress: 'אמריקן אקספרס',
  AppStrings.discover: 'Discover',
  AppStrings.dinersClub: 'דיינרס קלאב',
  AppStrings.jcb: 'JCB',
  AppStrings.others: 'אחר',
  AppStrings.selectPickImage: 'לחץ/בחר תמונה',
  AppStrings.gallery: 'גלריה',
  AppStrings.camera: 'מצלמה',
  AppStrings.noDataFound: 'לא נמצאו נתונים',
  AppStrings.areYourSureYouWantToLogout: 'האם אתה בטוח שברצונך להתנתק?',
  AppStrings.areYourSureYouWantToDeleteAccount: 'האם אתה בטוח שברצונך למחוק את החשבון?',
  AppStrings.yes: 'כן',
  AppStrings.no: 'לא',
  AppStrings.next: 'הבא',
  AppStrings.cancel: 'בטל',
  AppStrings.createNewPassword: 'צור סיסמה חדשה',
  AppStrings.yourNewPasswordMustBeUnique: 'הסיסמה החדשה שלך חייבת להיות ייחודית מאלה שהיו בשימוש בעבר',
  AppStrings.forgotPassword: 'שכחת סיסמה',
  AppStrings.signInToYourAccount: 'היכנס לחשבון שלך',
  AppStrings.usernameEmail: 'שם משתמש/דוא"ל',
  AppStrings.firstName: 'שם פרטי',
  AppStrings.lastName: 'שם משפחה',
  AppStrings.email: 'דוא"ל',
  AppStrings.password: 'סיסמה',
  AppStrings.newPassword: 'סיסמה חדשה',
  AppStrings.confirmPassword: 'אשר סיסמה',
  AppStrings.signIn: 'היכנס',
  AppStrings.signUp: 'הירשם',
  AppStrings.forgotYourPassword: 'שכחת את הסיסמה שלך?',
  AppStrings.dontHaveAnAccount: 'אין לך חשבון?',
  AppStrings.haveAnAccount: 'יש לך חשבון?',
  AppStrings.welcome: 'ברוך הבא!',
  AppStrings.registerYourAccount: 'הירשם לחשבון',
  AppStrings.registerHere: 'הירשם כאן!',
  AppStrings.create: 'צור',
  AppStrings.dontWorryItOccurs: 'אל תדאג! זה קורה לפעמים. אנא הזן את כתובת הדוא"ל המקושרת לחשבון שלך',
  AppStrings.sendCode: 'שלח קוד',
  AppStrings.otpVerification: 'אימות סיסמה חד פעמית',
  AppStrings.enterTheVerificationCode: 'הזן את קוד האימות ששלחנו זה עתה לכתובת הדוא"ל שלך',
  AppStrings.verify: 'אמת',
  AppStrings.didntRecievedCode: 'לא קיבלת את הקוד?',
  AppStrings.resend: 'שלח שוב',
  AppStrings.otpVerified: 'סיסמה חד פעמית אומתה!',
  AppStrings.passwordChanged: 'סיסמה שונתה!',
  AppStrings.yourOtpHasBeenVerified: 'הסיסמה החד פעמית שלך אומתה .בוא ניגש למלא את פרטיך',
  AppStrings.yourPasswordHasBeenChanged: 'הסיסמה שלך שונתה בהצלחה',
  AppStrings.resetPassword: 'איפוס סיסמה',
  AppStrings.or: 'או',
  AppStrings.resendIn: 'שלח שוב בעוד',
  AppStrings.sec: 'שניות',
  AppStrings.backToSignIn: 'חזרה להתחברות',
  AppStrings.home: 'בית',
  AppStrings.iCard: 'לוח אישי',
  AppStrings.categories: 'קטגוריות',
  AppStrings.seeAll: 'ראה הכל',
  AppStrings.settings: 'הגדרות',
  AppStrings.english: 'אנגלית',
  AppStrings.hebrew: 'עברית',
  AppStrings.hello: 'שלום!',
  AppStrings.dontMissTheChanceToScratch: 'אל תפספס את ההזדמנות לגרד את ה-כרטיס',
  AppStrings.recentlyViewed: 'נצפה לאחרונה',
  AppStrings.customCards: 'כרטיסים מותאמים אישית',
  AppStrings.allCategories: 'כל הקטגוריות',
  AppStrings.purchasedBoards: 'לוחות שנרכשו',
  AppStrings.personalizedBoards: 'לוחות מותאמים אישית',
  AppStrings.recommendedScratch: 'כרטיסי גירוד מומלצים',
  AppStrings.exp: 'תפוגה',
  AppStrings.purchaseDate: 'תאריך רכישה',
  AppStrings.download: 'הורד',
  AppStrings.profile: 'פרופיל',
  AppStrings.contactScratch: 'צור קשר עם Scratch',
  AppStrings.transactionDetails: 'פרטי עסקה',
  AppStrings.deleteAccount: 'מחק חשבון',
  AppStrings.faq: 'שאלות נפוצות',
  AppStrings.changePassword: 'שנה סיסמה',
  AppStrings.notificationPreferences: 'העדפות התראות',
  AppStrings.termsAndConditions: 'תנאים והגבלות',
  AppStrings.privacyPolicy: 'מדיניות פרטיות',
  AppStrings.howCanWeHelpYou: 'איך נוכל לעזור לך?',
  AppStrings.pleaseLetUsKnowWhyAreYou: 'אנא ספר לנו מדוע אתה מוחק את חשבונך?',
  AppStrings.search: 'חפש',
  AppStrings.payNow: 'שלם עכשיו',
  AppStrings.prefferedPaymentMethods: 'שיטות תשלום מועדפות',
  AppStrings.cardsUPIAndMore: 'כרטיסים, UPI ועוד',
  AppStrings.price: 'מחיר',
  AppStrings.pay: 'שלם',
  AppStrings.card: 'כרטיס',
  AppStrings.coinCurrency: 'מטבע דיגיטלי',
  AppStrings.addMore: 'הוסף עוד',
  AppStrings.addCard: 'הוסף כרטיס',
  AppStrings.cardNumber: 'מספר כרטיס',
  AppStrings.nameOnCard: 'שם על הכרטיס',
  AppStrings.expiryDate: 'תאריך תפוגה',
  AppStrings.cvv: 'CVV - שלוש ספרות בגב הכרטיס',
  AppStrings.payWithInstalledAppOrUseAnother: 'שלם עם אפליקציה מותקנת, או השתמש באחרות',
  AppStrings.save: 'שמור',
  AppStrings.name: 'שם',
  AppStrings.maskedExpiry: 'חודש/שנה',
  AppStrings.noCardsFound: 'לא נמצאו כרטיסים',
  AppStrings.scratched: 'כרטיסים שגורדו',
  AppStrings.aboutUs: 'אודותינו',
  AppStrings.fullName: 'שם מלא',
  AppStrings.emailId: 'מזהה דוא"ל',
  AppStrings.phoneNumber: 'מספר טלפון',
  AppStrings.address: 'כתובת',
  AppStrings.editProfile: 'ערוך פרופיל',
  AppStrings.submit: 'שלח',
  AppStrings.skip: 'דלג',
  AppStrings.gender: 'מין',
  AppStrings.popularCategories: 'קטגוריות פופולריות',
  AppStrings.warning: 'אזהרה!',
  AppStrings.totalNoOfPersonalizedBoard: 'מספר כולל של לוחות מותאמים אישית',
  AppStrings.totalNoOfCategoriesBoard: 'מספר כולל של לוחות לפי קטגוריות',
  AppStrings.createYourOwnPersonlisedCards: 'צור כרטיסים מותאמים אישית משלך',
  AppStrings.cardLimit: 'מגבלת כרטיסים',
  AppStrings.getNow: 'קבל עכשיו',
  AppStrings.personalisedCards: 'כרטיסים מותאמים אישית',
  AppStrings.previousCreatedCards: 'כרטיסים שנוצרו בעבר',
  AppStrings.personalisedQuestionnaire: 'שאלון מותאם אישית',
  AppStrings.enterMessage: 'הזן הודעה',
  AppStrings.noQuestionsFound: 'לא נמצאו שאלות',
  AppStrings.youNeedToPayForThisScratchCard: 'עליך לשלם עבור כרטיס הגירוד הזה',
  AppStrings.areYouSure: 'האם אתה בטוח?',
  AppStrings.youWantToSubmitTheResponse: 'האם ברצונך לשלוח את התשובה?',
  AppStrings.youWantToAddSupportTicket: 'האם ברצונך להוסיף כרטיס תמיכה?',
  AppStrings.confirm: 'אשר',
  AppStrings.pleaseSelectAnOption: 'אנא בחר אפשרות',
  AppStrings.transactionHistory: 'היסטוריית עסקאות',
  AppStrings.transactionAmount: 'סכום עסקה',
  AppStrings.transactionDate: 'תאריך עסקה',
  AppStrings.transactionId: 'מזהה עסקה',
  AppStrings.orderId: 'מזהה הזמנה',
  AppStrings.giveRating: 'תן דירוג',
  AppStrings.rating: 'דירוג!',
  AppStrings.add: 'הוסף',
  AppStrings.id: 'מזהה',
  AppStrings.date: 'תאריך',
  AppStrings.addTicket: 'הוסף כרטיס',
  AppStrings.title: 'כותרת',
  AppStrings.description: 'תיאור',
  AppStrings.createdOn: 'נוצר בתאריך:',
  AppStrings.typeAMessage: 'הקלד הודעה',
  AppStrings.admin: 'מנהל',
  AppStrings.dateOfBirth: 'תַאֲרִיך לֵידָה',
  AppStrings.youWantToMarkThisTicketAsComplete: 'האם ברצונך לסמן את כרטיס הגירוד כ-"הושלם"?',
  AppStrings.cost: 'עלות',
  AppStrings.type: 'סוג',
  AppStrings.ageGroup: 'קבוצת גיל',
  AppStrings.manageSubscription: 'ניהול מנוי',
  AppStrings.notifications: 'התראות',
  AppStrings.clear: 'נקה',
  AppStrings.payPal: 'פייפאל',
  AppStrings.purchase: 'רכישה',
  AppStrings.youWantToClearNotifications: 'האם אתה רוצה לנקות את ההתראות',
  AppStrings.connectionError: 'שגיאת חיבור',
  AppStrings.male: 'זכר',
  AppStrings.female: 'נקבה',
  AppStrings.paymentFailed: "לא הצלחנו לעבד את התשלום שלך. אנא בדוק ונסה שוב.",
  AppStrings.continueText: "המשך",
  AppStrings.note: "הערה",
  AppStrings.cryptoDialogDescriptionText: "לרכישת פרימיום באמצעות מטבעות קריפטוגרפיים (Tether/Ethereum), אנא צרו קשר עם המנהל דרך 'צור קשר עם Scratchy'.",
  AppStrings.thePurchasedBoardIsExpired: "תוקף הלוח שנרכש פג. עליך לרכוש חברות פרימיום כדי לגרד כרטיסים. האם ברצונך לרכוש פרימיום?",
  AppStrings.payViaCrypto: "שלם באמצעות קריפטו",
  AppStrings.youAreSubscribedToThePremiumMembership: "שלם באמצעות קריפטו",
  AppStrings.inAppPurchase: "רכישה בתוך האפליקציה",
  AppStrings.buyByCrypto: "קנייה באמצעות קריפטו",
  AppStrings.info: "מידע",
  AppStrings.areYouSureYouWantToGetThisBoard: "האם אתה בטוח שברצונך לרכוש את הלוח הזה?"







};